trigger:
  branches:
    include:
      - main
  paths:
    include:
      - main

pool:
  vmImage: ubuntu-latest

extends:
  template: ../utils/mfes.yml
  parameters:
    portal: konoha
    appName: main
    