trigger:
  branches:
    include:
      - main
  paths:
    include:
      - wrapper

variables:
  portal: konoha
  appName: wrapper
  imageName: $(portal)-$(appName)-$(Build.BuildId)

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: container-registry
  # - template: ../utils/js-setup.yml
  #   parameters:
  #     portal: $(portal)
  #     appName: $(appName)
  # - task: Docker@2
  #   displayName: Build an image
  #   inputs:
  #     containerRegistry: containerRegistry
  #     repository: $(imageName)
  #     command: build
  #     Dockerfile: ./Dockerfile
