trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ninjas

pool:
  vmImage: ubuntu-latest

steps:
  - template: ../utils/js-setup.yml
    parameters:
      portal: konoha
      appName: ninjas
  - template: ../utils/blob-storage.yml
    parameters:
      portal: konoha
      appName: ninjas
