trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ninjas

pool:
  vmImage: ubuntu-latest

extends:
  template: ../utils/mfes.yml
  parameters:
    portal: konoha
    appName: ninjas
